apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-rtiy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-rtiy
    app.kubernetes.io/part-of: cin4s-839-0075-app
  name: devfile-sample-rtiy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-rtiy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-rtiy
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0075-tenant/cin4s-839-0075-app/devfile-sample-rtiy@sha256:6f714d4959bd575e61cb5e82835d3cf09b2c008abfe1ef1939328b2633bdc2a7
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
